// <auto-generated />
using System;
using MagivVilla_VillaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagivVilla_VillaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230708203911_SeedVillaTableWithCreatedDate")]
    partial class SeedVillaTableWithCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagivVilla_VillaApi.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 7, 8, 23, 39, 11, 539, DateTimeKind.Local).AddTicks(2469),
                            Details = "The best of the best villa.",
                            ImageUrl = "https://dotnetmasteryimages.blog.core.windows.net/bluevillaimages/villa1.jpg",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 100.0,
                            Sqft = 150,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 7, 8, 23, 39, 11, 539, DateTimeKind.Local).AddTicks(2485),
                            Details = "The best of the best villa.",
                            ImageUrl = "https://dotnetmasteryimages.blog.core.windows.net/bluevillaimages/villa2.jpg",
                            Name = "Royal Villa2",
                            Occupancy = 6,
                            Rate = 200.0,
                            Sqft = 250,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 7, 8, 23, 39, 11, 539, DateTimeKind.Local).AddTicks(2488),
                            Details = "The best of the best villa.",
                            ImageUrl = "https://dotnetmasteryimages.blog.core.windows.net/bluevillaimages/villa3.jpg",
                            Name = "Royal Villa3",
                            Occupancy = 7,
                            Rate = 300.0,
                            Sqft = 350,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 7, 8, 23, 39, 11, 539, DateTimeKind.Local).AddTicks(2490),
                            Details = "The best of the best villa.",
                            ImageUrl = "https://dotnetmasteryimages.blog.core.windows.net/bluevillaimages/villa4.jpg",
                            Name = "Royal Villa4",
                            Occupancy = 8,
                            Rate = 400.0,
                            Sqft = 450,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 7, 8, 23, 39, 11, 539, DateTimeKind.Local).AddTicks(2492),
                            Details = "The best of the best villa.",
                            ImageUrl = "https://dotnetmasteryimages.blog.core.windows.net/bluevillaimages/villa5.jpg",
                            Name = "Royal Villa5",
                            Occupancy = 9,
                            Rate = 500.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
